version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Можете убрать это правило, если не хотите открывать Redis наружу
    networks:
      - mynetwork

  web:
    build: .
    container_name: Asmoran-server
    depends_on:
      - redis
    networks:
      - mynetwork
    environment:
      - REDIS_HOST=redis  # Указываем имя контейнера Redis как хост
      - REDIS_PORT=6379
    ports:
      - "8000:8000"

networks:
  mynetwork:
    driver: bridge
